export const homeObjOne = {
    id: 'about',
    lightBg: true,
    lightText: true,
    lightTextDesc: true,
    topLine: 'About Me',
    headline: '',
    description: 'Hi!  My name is Monil and I am a Texas based full-stack developer.\n\nI currently work as a Technical Project Manager in the IOT/Telematics division of an engine manufacturing company called Cummins Inc. My affinity towards software development started years ago in the form of some Matlab and C programming classes when I was pursuing my bachelors in Electrical Engineering at Purdue University. To be honest, being an international student on a student visa back then I did not think much of it and was happy to take the first job I got at 21.\n\nAs fate may have it, the first 4 years of my career were spent as a validation engineer developing automated test scripts to test the controls software of engines built by Cummins. The next 4 years I managed the software and calibration development process for the Cummins 12 Liter engine, while picking up an evening MBA from Kelley School of Business. While I was eager to apply my new skills, my affinity towards tech nudged me to take up a more hybrid role that challenged me on both fronts. Today I manage IOT projects with telematics providers to integrate Cummins digital solutions.\n\nArrive COVID. As cheesy as it sounds, it sent me through a much needed soul searching exercise and made me acknowledge my long suppressed desire to become a software developer. After ~6 months of self learning I decided to take the plunge and enrolled in a 6 month software engineering immersive program at Fullstack Academy which I graduated from in Apr 2021.\n\nWith this newfound clarity and purpose I cannot wait to grow and contribute in the ever evolving world of tech.',
    buttonLabel: 'Get Started',
    imgStart: true,
    img: require('../../images/svg-1.png').default,
    alt: 'dolly',
    dark: false,
    primary: true,
    darkText: true,
};

export const homeObjTwo = {
    id: 'journey',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Journey',
    headline: 'Login to your account at any time',
    description: 'We have you covered no matter where you are located. All you need is an internet connection and a phone or computer.',
    buttonLabel: 'Learn More',
    imgStart: true,
    img: require('../../images/svg-2.png').default,
    alt: 'mirror',
    dark: true,
    primary: true,
    darkText: false,
};


export const homeObjThree = {
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Join our Team',
    headline: 'Creating an account is extremely easy',
    description: 'Get everything setup and ready in under 10 minutes. All you need to do is add your information and you\'re are ready to go',
    buttonLabel: 'Start Now',
    imgStart: false,
    img: require('../../images/svg-3.png').default,
    alt: 'Credit Card',
    dark: false,
    primary: false,
    darkText: true,
};